#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 20 03:43:02 EDT 2021
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail

export xv_cxl_lib_path="/home/fpga/tools/Vivado/2022.2/data/xsim"
export xv_cxl_ip_path="$xv_cxl_lib_path/ip"
export xv_cpt_lib_path="/home/fpga/tools/Vivado/2022.2/data/simmodels/xsim/2022.2/lnx64/6.2.0/systemc/protected"
xv_ext_lib_path="/home/fpga/tools/Vivado/2022.2/data/simmodels/xsim/2022.2/lnx64/6.2.0/ext"
xv_lib_path="/home/fpga/tools/Vivado/2022.2/lib/lnx64.o/Rhel/8:/home/fpga/tools/Vivado/2022.2/lib/lnx64.o/Rhel:/home/fpga/tools/Vivado/2022.2/lib/lnx64.o"

xv_ref_path=${VIVADO_LOC:-"/home/fpga/tools/Vivado/2022.2"}
xv_lib_path="$xv_ref_path/lib/lnx64.o/Default:$xv_ref_path/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$xv_ref_path/data/simmodels/xsim/2022.2/lnx64/6.2.0/ext/protobuf:$xv_ref_path/data/xsim/ip/sim_qdma_cpp_v1_0:$xv_ref_path/data/xsim/ip/xscl:$xv_ref_path/data/xsim/ip/xtlm_ipc_v1_0:$xv_ref_path/data/xsim/ip/sim_qdma_sc_v1_0:$xv_ref_path/data/xsim/ip/xtlm_simple_interconnect_v1_0:$xv_ref_path/data/xsim/ip/xtlm_ap_ctrl_v1_0:$xv_ref_path/data/xsim/ip/sim_ddr_v1_0:$xv_ref_path/data/xsim/ip/common_cpp_v1_0:$xv_ref_path/data/xsim/ip/common_rpc_v1:$xv_ref_path/data/xsim/ip/xtlm:$xv_ref_path/data/xsim/ip/emu_perf_common_v1_0:$LD_LIBRARY_PATH

# simulate design
echo "xsim pfm_top_wrapper_behav -key {Behavioral:sim_1:Functional:pfm_top_wrapper} -tclbatch pfm_top_wrapper.tcl -protoinst "protoinst_files/bd_f615.protoinst" -protoinst "protoinst_files/bd_4bfa.protoinst" -protoinst "protoinst_files/bd_27a1.protoinst" -protoinst "protoinst_files/bd_e7f0.protoinst" -protoinst "protoinst_files/bd_2b97.protoinst" -protoinst "protoinst_files/bd_4688.protoinst" -protoinst "protoinst_files/bd_86d9.protoinst" -protoinst "protoinst_files/bd_8629.protoinst" -protoinst "protoinst_files/bd_4678.protoinst" -protoinst "protoinst_files/bd_87c9.protoinst" -protoinst "protoinst_files/bd_4798.protoinst" -protoinst "protoinst_files/bd_065e.protoinst" -protoinst "protoinst_files/bd_5607.protoinst" -protoinst "protoinst_files/bd_d216.protoinst" -protoinst "protoinst_files/bd_763a.protoinst" -protoinst "protoinst_files/bd_b62f.protoinst" -protoinst "protoinst_files/bd_76e2.protoinst" -protoinst "protoinst_files/bd_7606.protoinst" -protoinst "protoinst_files/bd_778a.protoinst" -protoinst "protoinst_files/bd_b79f.protoinst" -protoinst "protoinst_files/bd_b7e7.protoinst" -protoinst "protoinst_files/bd_5dca.protoinst" -protoinst "protoinst_files/pfm_dynamic.protoinst" -protoinst "protoinst_files/bd_387c.protoinst" -protoinst "protoinst_files/pfm_top.protoinst" -log simulate.log $*"
xsim pfm_top_wrapper_behav -key {Behavioral:sim_1:Functional:pfm_top_wrapper} -tclbatch pfm_top_wrapper.tcl -protoinst "protoinst_files/bd_f615.protoinst" -protoinst "protoinst_files/bd_4bfa.protoinst" -protoinst "protoinst_files/bd_27a1.protoinst" -protoinst "protoinst_files/bd_e7f0.protoinst" -protoinst "protoinst_files/bd_2b97.protoinst" -protoinst "protoinst_files/bd_4688.protoinst" -protoinst "protoinst_files/bd_86d9.protoinst" -protoinst "protoinst_files/bd_8629.protoinst" -protoinst "protoinst_files/bd_4678.protoinst" -protoinst "protoinst_files/bd_87c9.protoinst" -protoinst "protoinst_files/bd_4798.protoinst" -protoinst "protoinst_files/bd_065e.protoinst" -protoinst "protoinst_files/bd_5607.protoinst" -protoinst "protoinst_files/bd_d216.protoinst" -protoinst "protoinst_files/bd_763a.protoinst" -protoinst "protoinst_files/bd_b62f.protoinst" -protoinst "protoinst_files/bd_76e2.protoinst" -protoinst "protoinst_files/bd_7606.protoinst" -protoinst "protoinst_files/bd_778a.protoinst" -protoinst "protoinst_files/bd_b79f.protoinst" -protoinst "protoinst_files/bd_b7e7.protoinst" -protoinst "protoinst_files/bd_5dca.protoinst" -protoinst "protoinst_files/pfm_dynamic.protoinst" -protoinst "protoinst_files/bd_387c.protoinst" -protoinst "protoinst_files/pfm_top.protoinst" -log simulate.log $*

